[pytest]
addopts = -v --tb=short


markers =
    severity_critical: marks tests as critical severity
    severity_major: marks tests as major severity
    severity_minor: marks tests as minor severity
